import * as React from 'react'
import Head from 'next/head'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

import MainLayout from '@/components/layouts/MainLayout'
import { GetStaticProps } from 'next'
import PageTitle from '@/components/PageTitle'
import { useTranslation } from 'react-i18next'

export const getStaticProps: GetStaticProps = async () => ({
  props: {
    ...(await serverSideTranslations('fr', [
      'common'
    ]))
  }
})

const Home: React.FC = () => {
  const { t } = useTranslation([
    'common'
  ])

  return (
    <MainLayout>
      <PageTitle title={t('common:welcome')} />
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </MainLayout>
  )
}

export default Home
