import * as React from 'react'
import Head from 'next/head'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

import Switch from '@mui/material/Switch'
import MainLayout from '@/components/layouts/MainLayout'
import { GetStaticProps } from 'next'

export const getStaticProps: GetStaticProps = async () => ({
  props: {
    ...(await serverSideTranslations('fr', [
      'common'
    ]))
  }
})

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Compostage dans ma ville - POC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <h3>test</h3>
        <h3>test</h3>
        <h3>test</h3>
        <h3>test</h3>
        <h3>test</h3>
        <h3>test</h3>
        <h3>test</h3>
        <h3>test</h3>
        <h3>test</h3>
        <Switch defaultChecked />
      </MainLayout>
    </>
  )
}

export default Home
